### ISSUE TITLE
authlib-injector 登录失败

### ISSUE THREAD

**Issue by Trumeet** [xmdhs/gomclauncher#1]
```
$ gml -email [REDACTED] -password [REDACTED] -yggdrasil [REDACTED]
panic: 外置登录地址错误

goroutine 1 [running]:
github.com/xmdhs/gomclauncher/flag.Flag.Authlib(0xc0000b40c0, 0x15, 0x72482f, 0x4, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	github.com/xmdhs/gomclauncher/flag/Yggdrasil.go:19 +0x1ea
main.main()
	command-line-arguments/main.go:56 +0x523
```

希望这些信息有所帮助。

**Comment by xmdhs** [comment]
我是通过判断填写的 Yggdrasil API 地址中，是否有 `signaturePublickey` 字段来判断填写的外置登录地址是否正确的。

比如 https://littleskin.cn/api/yggdrasil 中就有的。应该都有吧。

所以我觉得可能是你这填错了。

**Comment by Trumeet** [comment]
> 我是通过判断填写的 Yggdrasil API 地址中，是否有 `signaturePublickey` 字段来判断填写的外置登录地址是否正确的。
> 
> 比如 https://littleskin.cn/api/yggdrasil 中就有的。应该都有吧。
> 
> 所以我觉得可能是你这填错了。

您好，我刚刚测试了一下，我填的地址也有 `signaturePublickey` 字段。

**Comment by Trumeet** [comment]
非常抱歉打扰您，我刚刚联系了网站站长，是网站检测到不寻常的 User Agent 之后拦截了，现已联系解决。
