### ISSUE TITLE
无法下载 1.18

### ISSUE THREAD

**Issue by brucekomike** [xmdhs/gomclauncher#13]

**Comment by brucekomike** [comment]
直接提示没有这个版本

**Comment by xmdhs** [comment]
加上 -type "vanilla" 或者多尝试几次。

镜像源还没完全同步 1.18 的一些文件。

**Comment by xmdhs** [comment]
https://bmclapi2.bangbang93.com/mc/game/version_manifest.json

现在镜像源已经同步，下载应该没有任何问题了
