### ISSUE TITLE
建议修改JVM默认参数为 "-XX:+UseConcMarkSweepGC"

### ISSUE THREAD

**Issue by Parollel** [xmdhs/gomclauncher#17]
我使用默认的JVM参数 "-XX:+UseG1GC" 运行1.12.2模组客户端(Forge,70个模组,Linux,Java8),在清理内存时帧数会大幅降低,导致游戏每隔一段时间就会卡顿。虽然会用命令行的人一般都知道修改参数,但我还是建议修改默认的JVM参数。

**Comment by xmdhs** [comment]
并不合适，因为如果用了 java 17，用 `UseConcMarkSweepGC` 就会报 `Unrecognized VM option 'UseConcMarkSweepGC'` 的

所以最好还是把选择给用户自己，不过可以考虑去除默认设置的 `-XX:+UseG1GC`，毕竟从 java 9 开始就已经默认是 g1gc 了

**Comment by Parollel** [comment]
试了一下 java 19 启动 1.18.2 报错,感谢纠正。
