### ISSUE TITLE
1.16.5无法启动

### ISSUE THREAD

**Issue by MakesYT** [xmdhs/gomclauncher#6]
![image](https://user-images.githubusercontent.com/42534870/109153420-da430080-77a7-11eb-81ac-a4b97857de58.png)

**Comment by xmdhs** [comment]
未能复现，能否描述下你用于启动的命令。以及安装 forge 的方式。

**Comment by MakesYT** [comment]
HMCL安装的ATM6

**Comment by MakesYT** [comment]
![image](https://user-images.githubusercontent.com/42534870/109157864-8e935580-77ad-11eb-98f1-da286597552f.png)

**Comment by xmdhs** [comment]
hmcl 的安装后的格式和官方启动器以及别的启动器的都不一样来着，所以也没有考虑去兼容的。

**Comment by MakesYT** [comment]
mmc的可以启动不？

**Comment by xmdhs** [comment]
你说的是 MultiMC 吧，那个更不一样了。设计之初是以官方的 json 格式来的，以及兼容 forge 和 fabric 安装器安装后的 json 文件。

如果你想用这个启动器来启动 hmcl 安装的整合包的话，可以尝试用 forge 的安装器安装，然后把 .minecraft 中的 config 文件夹和 mods 文件夹丢进去就应该没有什么大的问题了。

**Comment by xmdhs** [comment]
关于如何使用命令行安装 curseforge 的整合包，可以参照这里
https://github.com/ProjectHDS/Herodotus/blob/master/.github/workflows/dev.yml

**Comment by lengyefenghan** [comment]
建议试试gml启动器从mcbbs下载的1.16.5版本 我这里也是无法启动
